In [2]:
import numpy as np 

arr = [1, 2, 3, 4, 5]
np_arr = np.array(arr)
print(type(arr))
print(type(np_arr))


<class 'list'>
<class 'numpy.ndarray'>


- python의 range함수와 비슷하게 사용 가능

In [4]:
arr = np.arange(15)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


2차원 배열 생성

In [5]:
arr = np.arange(15).reshape(3, 5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


Indexing

In [7]:
arr = np.arange(25).reshape(5, 5)
print(arr)
print(arr[1][2])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
7


1번 , 2번행 / 0번, 1번열

In [8]:
print(arr[1:3,  :2])

[[ 5  6]
 [10 11]]


얕은 복사(원본은 변경하기 싫을 때) - np.copy() 함수 활용

In [9]:
arr2 = arr
arr2[0][0] = 15 
print(arr)
print(arr2)

[[15  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[15  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [10]:
arr = np.arange(15).reshape(3, 5)
arr2 = arr.copy()
arr2[0][0] = 15
print(arr)
print(arr2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[15  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
